version: '2'
services:
    exp-app:
        image: exp
        external_links:
            - exp-postgresql:postgresql
            - exp-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/exp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    exp-postgresql:
        extends:
            file: postgresql.yml
            service: exp-postgresql
    exp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: exp-elasticsearch
